// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXg2RLO336T_Iw_vcW7ZbJC1T8-oOhI2k',
    appId: '1:72105304780:web:007a9bb1296ef7dc8c9869',
    messagingSenderId: '72105304780',
    projectId: 'tropica-final',
    authDomain: 'tropica-final.firebaseapp.com',
    storageBucket: 'tropica-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDab20zheB7bsH7ihC2esEd5JvaYpXiYX0',
    appId: '1:72105304780:android:7addecde2fcf4d018c9869',
    messagingSenderId: '72105304780',
    projectId: 'tropica-final',
    storageBucket: 'tropica-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAec1UF3IfWgfjrLZI9F6HOvG_BzVE77o',
    appId: '1:72105304780:ios:13276718d3b193fe8c9869',
    messagingSenderId: '72105304780',
    projectId: 'tropica-final',
    storageBucket: 'tropica-final.firebasestorage.app',
    iosBundleId: 'com.example.tropicaGuideReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAec1UF3IfWgfjrLZI9F6HOvG_BzVE77o',
    appId: '1:72105304780:ios:13276718d3b193fe8c9869',
    messagingSenderId: '72105304780',
    projectId: 'tropica-final',
    storageBucket: 'tropica-final.firebasestorage.app',
    iosBundleId: 'com.example.tropicaGuideReal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXg2RLO336T_Iw_vcW7ZbJC1T8-oOhI2k',
    appId: '1:72105304780:web:8838ac11580771828c9869',
    messagingSenderId: '72105304780',
    projectId: 'tropica-final',
    authDomain: 'tropica-final.firebaseapp.com',
    storageBucket: 'tropica-final.firebasestorage.app',
  );
}
